[package]
name = "iso_639_macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
csv.workspace = true
proc-macro2.workspace = true 
quote.workspace = true
serde.workspace = true
syn.workspace = true

